# Generated by Django 3.0.7 on 2023-11-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='apogee',
            field=models.CharField(default='2051', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='cne',
            field=models.CharField(default='r12345', max_length=50),
        ),
    ]
